#!/bin/bash
currpath=${PWD}
scrpath=$(dirname $0)

gcc -nostdlib -m32 -fpic -masm=intel $currpath/main.c -o $currpath/main.bin
if [ $? -ne 0 ]; then
	echo "gcc error"
	exit -1;
fi
objcopy -O binary $currpath/main.bin
if [ $? -ne 0 ]; then
	echo "objcopy error"
	exit -1;
fi
nasm -f bin $scrpath/boot.asm -o $currpath/boot.bin
if [ $? -ne 0 ]; then
	echo "nasm error"
	exit -1;
fi

cp $scrpath/compile.py $currpath/compile.py
python3 $currpath/compile.py

rm $currpath/main.bin
rm $currpath/boot.bin
rm $currpath/compile.py

qemu-system-i386 $currpath/discpy.img
