#!/bin/bash
g++ -nostdlib -m32 -fpic -masm=intel core/main.cpp -o main.bin
if [ $? -ne 0 ]; then
	echo "gcc error"
	exit -1;
fi
objcopy -O binary main.bin
if [ $? -ne 0 ]; then
	echo "objcopy error"
	exit -1;
fi
nasm -f bin boot.asm -o boot.bin
if [ $? -ne 0 ]; then
	echo "nasm error"
	exit -1;
fi

python3 compile.py

rm main.bin
rm boot.bin
rm compile.py

qemu-system-i386 discpy.img
