#!/bin/bash
mkdir core/tmp
g++ -m32 -c core/math.cpp -o core/tmp/math.o
g++ -m32 -c core/video.cpp -o core/tmp/video.o
g++ -m32 -c core/window.cpp -o core/tmp/window.o
g++ -m32 -c core/stdio.cpp -o core/tmp/stdio.o
g++ -m32 -c -masm=intel -nostdlib -fpic core/CMOS.cpp -o core/tmp/CMOS.o
g++ -m32 -c -masm=intel -nostdlib -fpic core/disc.cpp -o core/tmp/disc.o

g++ -nostdlib -m32 -fpic -masm=intel core/main.cpp core/tmp/*.o -o main.bin
if [ $? -ne 0 ]; then
	echo "gcc error"
	exit -1;
fi
objcopy -O binary main.bin
if [ $? -ne 0 ]; then
	echo "objcopy error"
	exit -1;
fi
nasm -f bin boot.asm -o boot.bin
if [ $? -ne 0 ]; then
	echo "nasm error"
	exit -1;
fi

python3 compile.py

rm main.bin
rm boot.bin
rm core/tmp/*.o
rmdir core/tmp

qemu-system-i386 discpy.img
